# Generated by Django 3.2 on 2023-02-16 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('nomenclatura', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fechaestado', models.DateField(blank=True, null=True)),
                ('barrio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locacion.barrio')),
                ('calle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locacion.calle')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expediente.estado')),
            ],
            options={
                'verbose_name_plural': 'Expedientes',
            },
        ),
    ]
