# Generated by Django 3.2 on 2023-02-16 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacion', '0001_initial'),
        ('expediente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expediente',
            name='barrio',
        ),
        migrations.AddField(
            model_name='expediente',
            name='barrio',
            field=models.ManyToManyField(null=True, to='locacion.Barrio'),
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='calle',
        ),
        migrations.AddField(
            model_name='expediente',
            name='calle',
            field=models.ManyToManyField(null=True, to='locacion.Calle'),
        ),
    ]
