# Generated by Django 3.2 on 2023-02-16 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacion', '0001_initial'),
        ('expediente', '0003_alter_expediente_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='barrio',
            field=models.ManyToManyField(to='locacion.Barrio'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='calle',
            field=models.ManyToManyField(to='locacion.Calle'),
        ),
    ]
