# Generated by Django 3.2 on 2023-02-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacion', '0001_initial'),
        ('expediente', '0004_auto_20230216_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='barrio',
            field=models.ManyToManyField(blank=True, null=True, to='locacion.Barrio'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='calle',
            field=models.ManyToManyField(blank=True, null=True, to='locacion.Calle'),
        ),
    ]
