# Generated by Django 2.2 on 2023-03-01 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0006_auto_20230217_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoExpediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Expedientes',
            },
        ),
        migrations.AddField(
            model_name='expediente',
            name='tipoexpediente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expediente.TipoExpediente'),
        ),
    ]
