# Generated by Django 3.2 on 2023-03-02 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contratistas', '0001_initial'),
        ('expediente', '0007_auto_20230301_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tipoexpediente',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montooficial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montoadjudicado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contratista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratistas.contratista')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.expediente')),
            ],
            options={
                'verbose_name_plural': 'Obras',
            },
        ),
    ]
