# Generated by Django 3.2 on 2023-03-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0008_auto_20230302_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='nomenclatura',
            field=models.TextField(max_length=20, unique=True),
        ),
    ]
