# Generated by Django 3.2 on 2023-03-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacion', '0003_auto_20230302_2019'),
        ('expediente', '0011_auto_20230303_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='barrio',
            field=models.ManyToManyField(to='locacion.Barrio'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='calle',
            field=models.ManyToManyField(to='locacion.Calle'),
        ),
    ]
