# Generated by Django 3.2 on 2023-03-03 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0012_auto_20230303_1035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificado',
            options={'verbose_name_plural': 'Certificados'},
        ),
        migrations.AddField(
            model_name='certificado',
            name='expediente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='expediente.expediente'),
        ),
    ]
