# Generated by Django 3.2 on 2023-03-02 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacion', '0002_auto_20230217_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='calle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
